### ISSUE TITLE
[frontend] [proto] 順位表(standings) proto 見直し

### ISSUE THREAD

**Issue by h-takeyeah** [szpp-dev-team/szpp-judge#93]
9/30 の全体 MTG などで出た順位表関係で見直したいところをリストにしておくための issue
- 関連 PR
  - #92

**Comment by h-takeyeah** [comment]
### TODO 
- src/components/page/Standings/Standings.tsx
  - [x] let contestId = 1; // TODO: contestSlug から standings を取れるようにする
  - [ ] untilAc={1800000} // TODO: ペナルティを加味した untilAc 的な指標をバックエンドからもらう
- src/mocks/handlers/contest.ts
  - [ ] latestAcAt: undefined, // TODO: 削除?
  - [x] const { contestId } = await decodeReq(); // TODO: proto 更新して contest_slug にしたい

**Comment by h-takeyeah** [comment]
#94 と #92 がマージされて完了したのでクローズ
